version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - data:/data
    env_file:
      - ./.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  db:
    image: postgres:latest
    ports:
    - "5400:5432"
    env_file:
      - ./.env
volumes:
  data:
    external: false