version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - f:/Projects/codebases/miminani/backend:/app
    env_file:
      - backend/.env
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - f:/Projects/codebases/miminani/frontend:/app