"""empty message

Revision ID: f17134fe3cc9
Revises: 
Create Date: 2017-04-13 11:17:43.739703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17134fe3cc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baptism_name', sa.String(length=64), nullable=True),
    sa.Column('ethnic_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_persons_ethnic_name'), 'persons', ['ethnic_name'], unique=False)
    op.create_index(op.f('ix_persons_last_name'), 'persons', ['last_name'], unique=False)
    op.create_table('links',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('link_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ascendant_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['descendant_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('ascendant_id', 'descendant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_index(op.f('ix_persons_last_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_ethnic_name'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
